### ISSUE TITLE
OS Choose

### ISSUE THREAD

**Issue by 0n1cOn3** [0n1cOn3/Shodan-IP-Scan-Resulter#2]
Theres a bug, which i am can't fix. 

Its going to be, which OS is running and from there the script chooses the correct breakpoint.

**Comment by TheSpeedX** [comment]
@0n1cOn3 So u fixed that?
 And Delete That .DS_Store File I forgot to delete

**Comment by 0n1cOn3** [comment]
@TheSpeedX 

Yes :) 

kk
